CREATE TABLE "chatbot_chat" (
	"id" varchar(256) PRIMARY KEY NOT NULL,
	"messages" json DEFAULT '[]'::json NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "chatbot_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chatbot_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "chat_created_idx" ON "chatbot_chat" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "name_idx" ON "chatbot_post" USING btree ("name");